[mega]
type = mega
user = TU_EMAIL_MEGA
pass = TU_CONTRASEÑA_MEGA

[mega-crypted]
type = crypt
remote = mega:
filename_encryption = standard
password = CONTRASEÑA_ENCRIPCIÓN_FICHEROS
password2 = CONTRASEÑA_ENCRIPCIÓN_NOMBRES